### PR TITLE
Smfun12-hw1

### PR DESCRIPTION
**Pull request by Smfun12**

### CODE REVIEW

**Comment by KyloRen1** [comment]
Cell 130 has a useless output of words
Cell 137 has to output two numbers, consider adding `print`

**Review by KyloRen1 — COMMENTED** [review]
все погано

**Review by KyloRen1 — APPROVED** [review]
LGTM

**Review by BRomanchuk — APPROVED** [review]
22] can be optimized using numpy (it will work faster)
24] can be compressed:)
30] plot has different clusters than in other HWs (not sure whether it happened accidentally or somewhere is a mistake)
35] same as 30]

looks ok

**Pull request merged**
